# Generated by Django 4.1.7 on 2023-03-21 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[[1, 1], [2, 2], [3, 3], [4, 4], [5, 5]], default=None)),
                ('date', models.DateField(auto_now=True)),
                ('reviewarea', models.TextField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.blog')),
            ],
        ),
    ]
